version: '3.9'
services:
    influx2:
        image: influxdb:2.6-alpine
        ports:
            - 8086:8086
        volumes:
            - ./docker/influx:/var/lib/influxdb2

    grafana:
        image: grafana/grafana:8.3.2
        ports:
            - 3000:3000
        volumes:
            - ./docker/grafana:/var/lib/grafana
        depends_on:
            - influx2

    worker:
        build:
            context: .
        depends_on:
            - influx2
        environment:
            APP_INTERVAL: 2
            INFLUX_HOST: "http://influx2:8086"
            INFLUX_TOKEN: "dri9PNEXl-NMvD6rOsv_i8A1ZnJB89pjep3hIOZVvBUAWV7I-GmObnckoLk-Ba5Qst0YDXS682dsclj9Xspq0g=="
            INFLUX_ORG: "admin"
            INFLUX_BUCKET: "speedtest"